cat checker_sap.yml
---
- name: Checker SAP pour SLES 15
  hosts: all
  become: yes
  gather_facts: yes

  tasks:
    - name: "Nom serveur"
      command: "hostname -f"
      register: server_name

    - name: "Version OS"
      command: "cat /etc/*rel* |grep PRETTY_NAME"
      register: version_os

    - name: "Ensure cron daemon is enabled"
      systemd:
        name: cron
        enabled: yes
      register: cron_status

    # Ajouter plus des controls

    - name: Generer le rapport
      template:
        src: checker_sap_raport.j2
        dest: checker_sap_raport.txt

cat checker_sap_controls.yml
checker_sap_controls:
  - name: "Ensure cron daemon is enabled"
    expected_result: "True"
    actual_result: "{{ cron_status.enabled }}"
  # Ajouter plus des controles SAP

cat checker_sap_raport.j2
Raport de conformite pour la securite SAP des serveurs SLES 15
==============================================================
Nom serveur: {{ server_name }}
Version de l'os: {{ version_os }}

{% for control in checker_sap_controls %}
Nom Control: {{ control.name }}
Resultat Attendu: {{ control.expected_result }}
Resultat Actuel: {{ control.actual_result }}
Status: {% if control.expected_result == control.actual_result %}Pass{% else %}Fail{% endif %}

{% endfor %}

[ransible@lcent7srvlabotest1 checker_sles_test2]$ 
