- name: Find local users starting with ct20
  hosts: all
  tasks:
    - name: Get hostname
      debug:
        var: ansible_hostname

    - name: Get local users
      shell: getent passwd
      register: local_users

    - name: Generate report
      template:
        src: report.j2
        dest: /tmp/report.txt
      vars:
        - users: "{{ local_users.stdout_lines }}"
        - hostname: "{{ ansible_hostname }}"

============================================
Jinja template - report.j2

Hostname: {{ hostname }}

{% for user in users %}
{% if user.startswith('ct20') %}
Username: {{ user.split(':')[0] }}
UID: {{ user.split(':')[3] }}
Home directory: {{ user.split(':')[5] }}
Shell: {{ user.split(':')[6] }}

{% endif %}
{% endfor %}
