---
- name: Find .gnupg folders and print results
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Get list of local users
      command: "getent passwd"
      changed_when: false
      register: passwd_output

    - name: Parse local users
      set_fact:
        local_users: "{{ passwd_output.stdout_lines | map('regex_replace', '^(.*?):.*$', '\\1') | list }}"

    - name: Search for .gnupg folders
      find:
        paths: "~{{ item }}/"
        patterns: ".gnupg"
      register: gnupg_folders
      loop: "{{ local_users }}"
      become: true

    - name: Create output file
      local_action: copy content=""
                   dest="gnupg_results.txt"
                   mode="0644"
      run_once: true

    - name: Append results to output file
      lineinfile:
        path: "gnupg_results.txt"
        line: "{{ item.item }}: {{ 'Found' if item.matched > 0 else 'Not found' }}"
      loop: "{{ gnupg_folders.results }}"
      run_once: true