---
- name: Check if users exist
  hosts: your_target_server
  gather_facts: False

  vars:
    users_file: /path/to/users.txt

  tasks:
    - name: Read users from file
      command: cat "{{ users_file }}"
      register: users_content
      changed_when: False

    - name: Verify users exist
      shell: "getent passwd {{ item }}"
      with_lines: "{{ users_content.stdout_lines }}"
      register: user_exists
      ignore_errors: True

    - name: Display existing users
      debug:
        msg: "User {{ item.item }} exists"
      loop: "{{ user_exists.results }}"
      when: item.rc == 0