---
- name: Check if users exist
  hosts: your_target_server
  gather_facts: False

  vars:
    users_file: /path/to/users.txt

  tasks:
    - name: Read users from file
      slurp:
        src: "{{ users_file }}"
      register: users_content

    - name: Verify users exist
      shell: "getent passwd {{ item }}"
      with_items: "{{ users_content['content'] | b64decode | split('\n') }}"
      register: user_exists
      ignore_errors: True

    - name: Display existing users
      debug:
        msg: "User {{ item.item }} exists"
      loop: "{{ user_exists.results }}"
      when: item.rc == 0