---
- name: Raspberry PI configuration
  hosts: labotest
  gather_facts: yes
  vars:
    hostname: "lubusrvlabotest1"
  tasks:
    - name: change hostname
      hostname:
        name: "{{ hostname }}"
