---
- name: Install optional packages
  package:
    name:
      - ufw
      - auditd
      - audispd-plugins
      - acct
    state: latest

- name: Remove optional packages
  package:
    name:
      - vim
      - acct
      - ca-certificates
      - wget
      - net-tools
    state: absent