---
- name: linux Debian configuration
  hosts: laboubuntu
  gather_facts: yes
  tasks:
    - import_tasks: bashrc.yml
    - import_tasks: userconfig.yml
    - import_tasks: sshconfig.yml
    - import_tasks: installpkg.yml
    - import_tasks: configure_ufw.yml
    - import_tasks: change_perm.yml
    - import_tasks: audit_rules.yml
    - import_tasks: motd.yml
    - import_tasks: ubuntuupdate.yml
#    - import_tasks: unifiController.yml