
---
# its not working !!!
- name: Change password to default
  ansible.netcommon.cli_command:
    command: "passwd ubuntu"
    prompt:
      - "New password"
      - "Retype new password"
    answer:
      - "password123"
      - "password123"
    check_all: True