---
- name: Update APT package cache
  apt: update_cache=yes cache_valid_time=3600
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Upgrade APT to the latest packages
  apt: upgrade=safe
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Adjust APT update intervals
  copy: src=files/apt_periodic dest=/etc/apt/apt.conf.d/10periodic
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
