---
- name: Setup | create user
  user:
    name: "ransible"
    comment: "usuario ransible creado por Ansible"
    groups: "sudo"
    shell: /bin/bash
    createhome: yes
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa
    state: "present"

- name: Add deploy user to sudoers
  lineinfile: dest=/etc/sudoers
    regexp="ransible ALL"
    line="ransible ALL=(ALL) NOPASSWD:ALL"
    state=present

- name: Setup | authorized key upload
  authorized_key: user="ransible"
    key="{{ lookup('file', 'files/id_ed25519.pub') }}"
    path='/home/ransible/.ssh/authorized_keys'
    manage_dir=no
